#!/bin/bash

system_type=$(uname -s)
if [ "$system_type" != "Darwin" ]; then
  echo "This isn't MacOS, exiting o/"
  exit 1
fi

# Submodules
yadm submodule update --recursive --init --remote

# Homebrew
echo "Applying Brewfile..."
brew bundle --global

# iTerm2
echo "Setting iTerm preference folder..."
defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"

# Vim
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim..."
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

echo "Enjoy! \o/"
